spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: core

resident-id:
  hmac-key: ${RESIDENT_ID_HMAC_KEY}
  encryption-key: ${RESIDENT_ID_ENCRYPTION_KEY}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level trace_id=%X{trace_id:-} span_id=%X{span_id:-} %logger{36} %kvp - %msg%n"
