plugins {
    id 'jacoco'
}

dependencies {
    implementation platform("software.amazon.awssdk:bom:${awsSdkVersion}")
    implementation project(':common-core')
    implementation 'software.amazon.awssdk:sqs'
    implementation 'software.amazon.awssdk:sts'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.opentelemetry:opentelemetry-api:1.62.0'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

jacoco {
    toolVersion = '0.8.12'
}

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test

    reports {
        html.required = true
        xml.required = true
        csv.required = false
    }

    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, exclude: [
                '**/PaymentApplication*',
                '**/*Controller*',
                '**/*Config*',
                '**/repository/**',
                '**/global/**'
        ])
    }))
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

bootRun {
    jvmArgs = [
            '-Dfile.encoding=UTF-8',
            '-Dsun.stdout.encoding=UTF-8',
            '-Dsun.stderr.encoding=UTF-8'
    ]
}
