spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: core
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

resident-id:
  hmac-key: ${RESIDENT_ID_HMAC_KEY}
  encryption-key: ${RESIDENT_ID_ENCRYPTION_KEY}