jwt:
  secret: ${JWT_SECRET}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: core
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    s3:
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET}
      kms-key-arn: ${AWS_S3_KMS_KEY_ARN:}
