name: Java CI with Gradle

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      # 👈 자바 버전을 21로 매핑하여 빌드 환경을 일치시킵니다.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build