name: Java CI with Gradle

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@<checkout-full-commit-sha>
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@<setup-java-full-commit-sha>
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build